SCREEN_WIDTH = 640
SCREEN_HEIGHT = 360
TILE_SIZE = 20
TILE_X_COUNT = SCREEN_WIDTH / TILE_SIZE
TILE_Y_COUNT = SCREEN_HEIGHT / TILE_SIZE
TOP_TILE_OFFSET = 50
MAX_DIM_TINT = 102

Vector = MiniGL::Vector
